# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (0971d1bb-305e-41b5-8473-fed72dd91161)'
    appType: 'webApp'
    WebAppName: 'Pros-Of-Cons'
    packageForLinux: '$(System.DefaultWorkingDirectory)'

- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true
    force32bit: true